### ISSUE TITLE
Get test suite working again

### ISSUE THREAD

**Issue by shaunagm** [shaunagm/bridge_troll#10]
We should really, really do this, @paulproteus.

**Comment by paulproteus** [comment]
+1

**Comment by shaunagm** [comment]
Current status: errors (http://pastebin.mozilla.org/8265515) and https://github.com/shaunagm/bridge_troll/commit/801dd21fc0582235a69dfdbcc7f24776e18dd854

**Comment by shaunagm** [comment]
Fixed by https://github.com/shaunagm/bridge_troll/commit/10e99e769b311d43bcd01c95df3884cf8efeac08, with tons of thanks due to @brendankemp.
