### ISSUE TITLE
Add space for content in chapters

### ISSUE THREAD

**Issue by shaunagm** [shaunagm/bridge_troll#3]
It would be great to have a paragraph or two on chapter pages that, at minimum, links to the discourse chapter category (so people who find the chapter can see conversations about events that are being planned, not just already planned events).  It would also be nice to have info on chapter leaders, although doing that through the data model may be a separate issue.

**Comment by shaunagm** [comment]
I added a "chapter_description" field to the database, model, view, etc.  You can now add a plain text description to the chapter!  I can't figure out how to get it to accept html, although there are other forms on BridgeTroll that do.  Another day!  FYI [this page](http://guides.rubyonrails.org/v3.2.19/migrations.html) was flawless at helping me understand what I needed to do.

Also, apparently chapter leaders are [already a thing](https://github.com/railsbridge/bridge_troll/tree/9e2faabfd35715e04fcecf4acd552e830aab2203/app/views/chapter_leaderships), just... quietly.

Moving to low priority milestone, will close when we get rich text content descriptions, since we want the links to Discourse to look nice.

**Comment by shaunagm** [comment]
Just needed to add html_safe to the variable in the view.  Easy peasy.

**Comment by shaunagm** [comment]
@paulproteus, is this a security issue?

**Comment by paulproteus** [comment]
It depends what `html_safe` does! I will talk to gwillen.
